package awtk;


public enum MIME_TYPE {
  APPLICATION_ENVOY (MIME_TYPE_APPLICATION_ENVOY()),
  APPLICATION_FRACTALS (MIME_TYPE_APPLICATION_FRACTALS()),
  APPLICATION_FUTURESPLASH (MIME_TYPE_APPLICATION_FUTURESPLASH()),
  APPLICATION_HTA (MIME_TYPE_APPLICATION_HTA()),
  APPLICATION_JSON (MIME_TYPE_APPLICATION_JSON()),
  APPLICATION_UBJSON (MIME_TYPE_APPLICATION_UBJSON()),
  APPLICATION_MAC_BINHEX40 (MIME_TYPE_APPLICATION_MAC_BINHEX40()),
  APPLICATION_MSWORD (MIME_TYPE_APPLICATION_MSWORD()),
  APPLICATION_OCTET_STREAM (MIME_TYPE_APPLICATION_OCTET_STREAM()),
  APPLICATION_ODA (MIME_TYPE_APPLICATION_ODA()),
  APPLICATION_OLESCRIPT (MIME_TYPE_APPLICATION_OLESCRIPT()),
  APPLICATION_PDF (MIME_TYPE_APPLICATION_PDF()),
  APPLICATION_PICS_RULES (MIME_TYPE_APPLICATION_PICS_RULES()),
  APPLICATION_PKCS10 (MIME_TYPE_APPLICATION_PKCS10()),
  APPLICATION_PKIX_CRL (MIME_TYPE_APPLICATION_PKIX_CRL()),
  APPLICATION_POSTSCRIPT (MIME_TYPE_APPLICATION_POSTSCRIPT()),
  APPLICATION_RTF (MIME_TYPE_APPLICATION_RTF()),
  APPLICATION_VND_MS_EXCEL (MIME_TYPE_APPLICATION_VND_MS_EXCEL()),
  APPLICATION_VND_MS_OUTLOOK (MIME_TYPE_APPLICATION_VND_MS_OUTLOOK()),
  APPLICATION_VND_MS_PKICERTSTORE (MIME_TYPE_APPLICATION_VND_MS_PKICERTSTORE()),
  APPLICATION_VND_MS_PKISECCAT (MIME_TYPE_APPLICATION_VND_MS_PKISECCAT()),
  APPLICATION_VND_MS_PKISTL (MIME_TYPE_APPLICATION_VND_MS_PKISTL()),
  APPLICATION_VND_MS_POWERPOINT (MIME_TYPE_APPLICATION_VND_MS_POWERPOINT()),
  APPLICATION_VND_MS_PROJECT (MIME_TYPE_APPLICATION_VND_MS_PROJECT()),
  APPLICATION_VND_MS_WORKS (MIME_TYPE_APPLICATION_VND_MS_WORKS()),
  APPLICATION_WINHLP (MIME_TYPE_APPLICATION_WINHLP()),
  APPLICATION_X_BCPIO (MIME_TYPE_APPLICATION_X_BCPIO()),
  APPLICATION_X_CDF (MIME_TYPE_APPLICATION_X_CDF()),
  APPLICATION_X_COMPRESS (MIME_TYPE_APPLICATION_X_COMPRESS()),
  APPLICATION_X_COMPRESSED (MIME_TYPE_APPLICATION_X_COMPRESSED()),
  APPLICATION_X_CPIO (MIME_TYPE_APPLICATION_X_CPIO()),
  APPLICATION_X_CSH (MIME_TYPE_APPLICATION_X_CSH()),
  APPLICATION_X_DIRECTOR (MIME_TYPE_APPLICATION_X_DIRECTOR()),
  APPLICATION_X_DVI (MIME_TYPE_APPLICATION_X_DVI()),
  APPLICATION_X_GTAR (MIME_TYPE_APPLICATION_X_GTAR()),
  APPLICATION_X_GZIP (MIME_TYPE_APPLICATION_X_GZIP()),
  APPLICATION_X_HDF (MIME_TYPE_APPLICATION_X_HDF()),
  APPLICATION_X_IPHONE (MIME_TYPE_APPLICATION_X_IPHONE()),
  APPLICATION_X_JAVASCRIPT (MIME_TYPE_APPLICATION_X_JAVASCRIPT()),
  APPLICATION_X_LATEX (MIME_TYPE_APPLICATION_X_LATEX()),
  APPLICATION_X_MSACCESS (MIME_TYPE_APPLICATION_X_MSACCESS()),
  APPLICATION_X_MSCARDFILE (MIME_TYPE_APPLICATION_X_MSCARDFILE()),
  APPLICATION_X_MSCLIP (MIME_TYPE_APPLICATION_X_MSCLIP()),
  APPLICATION_X_MSDOWNLOAD (MIME_TYPE_APPLICATION_X_MSDOWNLOAD()),
  APPLICATION_X_MSMEDIAVIEW (MIME_TYPE_APPLICATION_X_MSMEDIAVIEW()),
  APPLICATION_X_MSMETAFILE (MIME_TYPE_APPLICATION_X_MSMETAFILE()),
  APPLICATION_X_MSMONEY (MIME_TYPE_APPLICATION_X_MSMONEY()),
  APPLICATION_X_MSPUBLISHER (MIME_TYPE_APPLICATION_X_MSPUBLISHER()),
  APPLICATION_X_MSSCHEDULE (MIME_TYPE_APPLICATION_X_MSSCHEDULE()),
  APPLICATION_X_MSTERMINAL (MIME_TYPE_APPLICATION_X_MSTERMINAL()),
  APPLICATION_X_MSWRITE (MIME_TYPE_APPLICATION_X_MSWRITE()),
  APPLICATION_X_NETCDF (MIME_TYPE_APPLICATION_X_NETCDF()),
  APPLICATION_X_PERFMON (MIME_TYPE_APPLICATION_X_PERFMON()),
  APPLICATION_X_PKCS12 (MIME_TYPE_APPLICATION_X_PKCS12()),
  APPLICATION_X_SH (MIME_TYPE_APPLICATION_X_SH()),
  APPLICATION_X_SHAR (MIME_TYPE_APPLICATION_X_SHAR()),
  APPLICATION_X_SHOCKWAVE_FLASH (MIME_TYPE_APPLICATION_X_SHOCKWAVE_FLASH()),
  APPLICATION_X_STUFFIT (MIME_TYPE_APPLICATION_X_STUFFIT()),
  APPLICATION_X_SV4CPIO (MIME_TYPE_APPLICATION_X_SV4CPIO()),
  APPLICATION_X_SV4CRC (MIME_TYPE_APPLICATION_X_SV4CRC()),
  APPLICATION_X_TAR (MIME_TYPE_APPLICATION_X_TAR()),
  APPLICATION_X_TCL (MIME_TYPE_APPLICATION_X_TCL()),
  APPLICATION_X_TEX (MIME_TYPE_APPLICATION_X_TEX()),
  APPLICATION_X_TEXINFO (MIME_TYPE_APPLICATION_X_TEXINFO()),
  APPLICATION_X_TROFF (MIME_TYPE_APPLICATION_X_TROFF()),
  APPLICATION_X_USTAR (MIME_TYPE_APPLICATION_X_USTAR()),
  APPLICATION_ZIP (MIME_TYPE_APPLICATION_ZIP()),
  AUDIO_BASIC (MIME_TYPE_AUDIO_BASIC()),
  AUDIO_MID (MIME_TYPE_AUDIO_MID()),
  AUDIO_MPEG (MIME_TYPE_AUDIO_MPEG()),
  AUDIO_X_AIFF (MIME_TYPE_AUDIO_X_AIFF()),
  AUDIO_X_MPEGURL (MIME_TYPE_AUDIO_X_MPEGURL()),
  AUDIO_X_WAV (MIME_TYPE_AUDIO_X_WAV()),
  IMAGE_BMP (MIME_TYPE_IMAGE_BMP()),
  IMAGE_CIS_COD (MIME_TYPE_IMAGE_CIS_COD()),
  IMAGE_GIF (MIME_TYPE_IMAGE_GIF()),
  IMAGE_IEF (MIME_TYPE_IMAGE_IEF()),
  IMAGE_JPEG (MIME_TYPE_IMAGE_JPEG()),
  IMAGE_PIPEG (MIME_TYPE_IMAGE_PIPEG()),
  IMAGE_SVG_XML (MIME_TYPE_IMAGE_SVG_XML()),
  IMAGE_TIFF (MIME_TYPE_IMAGE_TIFF()),
  IMAGE_X_CMX (MIME_TYPE_IMAGE_X_CMX()),
  IMAGE_X_ICON (MIME_TYPE_IMAGE_X_ICON()),
  IMAGE_X_RGB (MIME_TYPE_IMAGE_X_RGB()),
  IMAGE_X_XBITMAP (MIME_TYPE_IMAGE_X_XBITMAP()),
  IMAGE_X_XPIXMAP (MIME_TYPE_IMAGE_X_XPIXMAP()),
  IMAGE_X_XWINDOWDUMP (MIME_TYPE_IMAGE_X_XWINDOWDUMP()),
  MESSAGE_RFC822 (MIME_TYPE_MESSAGE_RFC822()),
  TEXT_CSS (MIME_TYPE_TEXT_CSS()),
  TEXT_H323 (MIME_TYPE_TEXT_H323()),
  TEXT_HTML (MIME_TYPE_TEXT_HTML()),
  TEXT_IULS (MIME_TYPE_TEXT_IULS()),
  TEXT_PLAIN (MIME_TYPE_TEXT_PLAIN()),
  TEXT_RICHTEXT (MIME_TYPE_TEXT_RICHTEXT()),
  TEXT_SCRIPTLET (MIME_TYPE_TEXT_SCRIPTLET()),
  TEXT_WEBVIEWHTML (MIME_TYPE_TEXT_WEBVIEWHTML()),
  TEXT_X_COMPONENT (MIME_TYPE_TEXT_X_COMPONENT()),
  TEXT_X_SETEXT (MIME_TYPE_TEXT_X_SETEXT()),
  TEXT_X_VCARD (MIME_TYPE_TEXT_X_VCARD()),
  VIDEO_MPEG (MIME_TYPE_VIDEO_MPEG()),
  VIDEO_QUICKTIME (MIME_TYPE_VIDEO_QUICKTIME()),
  VIDEO_X_MSVIDEO (MIME_TYPE_VIDEO_X_MSVIDEO());
 
   
  private String value;
  MIME_TYPE(String value) {
    this.value = value;
  }
  public String value() {
    return this.value;
  }

  public static MIME_TYPE from(String value) {
    for(MIME_TYPE iter : MIME_TYPE.values()) {
      if(iter.value() == value) {
        return iter;
      }
    }

    return APPLICATION_ENVOY;
  }

  static private native String MIME_TYPE_APPLICATION_ENVOY();
  static private native String MIME_TYPE_APPLICATION_FRACTALS();
  static private native String MIME_TYPE_APPLICATION_FUTURESPLASH();
  static private native String MIME_TYPE_APPLICATION_HTA();
  static private native String MIME_TYPE_APPLICATION_JSON();
  static private native String MIME_TYPE_APPLICATION_UBJSON();
  static private native String MIME_TYPE_APPLICATION_MAC_BINHEX40();
  static private native String MIME_TYPE_APPLICATION_MSWORD();
  static private native String MIME_TYPE_APPLICATION_OCTET_STREAM();
  static private native String MIME_TYPE_APPLICATION_ODA();
  static private native String MIME_TYPE_APPLICATION_OLESCRIPT();
  static private native String MIME_TYPE_APPLICATION_PDF();
  static private native String MIME_TYPE_APPLICATION_PICS_RULES();
  static private native String MIME_TYPE_APPLICATION_PKCS10();
  static private native String MIME_TYPE_APPLICATION_PKIX_CRL();
  static private native String MIME_TYPE_APPLICATION_POSTSCRIPT();
  static private native String MIME_TYPE_APPLICATION_RTF();
  static private native String MIME_TYPE_APPLICATION_VND_MS_EXCEL();
  static private native String MIME_TYPE_APPLICATION_VND_MS_OUTLOOK();
  static private native String MIME_TYPE_APPLICATION_VND_MS_PKICERTSTORE();
  static private native String MIME_TYPE_APPLICATION_VND_MS_PKISECCAT();
  static private native String MIME_TYPE_APPLICATION_VND_MS_PKISTL();
  static private native String MIME_TYPE_APPLICATION_VND_MS_POWERPOINT();
  static private native String MIME_TYPE_APPLICATION_VND_MS_PROJECT();
  static private native String MIME_TYPE_APPLICATION_VND_MS_WORKS();
  static private native String MIME_TYPE_APPLICATION_WINHLP();
  static private native String MIME_TYPE_APPLICATION_X_BCPIO();
  static private native String MIME_TYPE_APPLICATION_X_CDF();
  static private native String MIME_TYPE_APPLICATION_X_COMPRESS();
  static private native String MIME_TYPE_APPLICATION_X_COMPRESSED();
  static private native String MIME_TYPE_APPLICATION_X_CPIO();
  static private native String MIME_TYPE_APPLICATION_X_CSH();
  static private native String MIME_TYPE_APPLICATION_X_DIRECTOR();
  static private native String MIME_TYPE_APPLICATION_X_DVI();
  static private native String MIME_TYPE_APPLICATION_X_GTAR();
  static private native String MIME_TYPE_APPLICATION_X_GZIP();
  static private native String MIME_TYPE_APPLICATION_X_HDF();
  static private native String MIME_TYPE_APPLICATION_X_IPHONE();
  static private native String MIME_TYPE_APPLICATION_X_JAVASCRIPT();
  static private native String MIME_TYPE_APPLICATION_X_LATEX();
  static private native String MIME_TYPE_APPLICATION_X_MSACCESS();
  static private native String MIME_TYPE_APPLICATION_X_MSCARDFILE();
  static private native String MIME_TYPE_APPLICATION_X_MSCLIP();
  static private native String MIME_TYPE_APPLICATION_X_MSDOWNLOAD();
  static private native String MIME_TYPE_APPLICATION_X_MSMEDIAVIEW();
  static private native String MIME_TYPE_APPLICATION_X_MSMETAFILE();
  static private native String MIME_TYPE_APPLICATION_X_MSMONEY();
  static private native String MIME_TYPE_APPLICATION_X_MSPUBLISHER();
  static private native String MIME_TYPE_APPLICATION_X_MSSCHEDULE();
  static private native String MIME_TYPE_APPLICATION_X_MSTERMINAL();
  static private native String MIME_TYPE_APPLICATION_X_MSWRITE();
  static private native String MIME_TYPE_APPLICATION_X_NETCDF();
  static private native String MIME_TYPE_APPLICATION_X_PERFMON();
  static private native String MIME_TYPE_APPLICATION_X_PKCS12();
  static private native String MIME_TYPE_APPLICATION_X_SH();
  static private native String MIME_TYPE_APPLICATION_X_SHAR();
  static private native String MIME_TYPE_APPLICATION_X_SHOCKWAVE_FLASH();
  static private native String MIME_TYPE_APPLICATION_X_STUFFIT();
  static private native String MIME_TYPE_APPLICATION_X_SV4CPIO();
  static private native String MIME_TYPE_APPLICATION_X_SV4CRC();
  static private native String MIME_TYPE_APPLICATION_X_TAR();
  static private native String MIME_TYPE_APPLICATION_X_TCL();
  static private native String MIME_TYPE_APPLICATION_X_TEX();
  static private native String MIME_TYPE_APPLICATION_X_TEXINFO();
  static private native String MIME_TYPE_APPLICATION_X_TROFF();
  static private native String MIME_TYPE_APPLICATION_X_USTAR();
  static private native String MIME_TYPE_APPLICATION_ZIP();
  static private native String MIME_TYPE_AUDIO_BASIC();
  static private native String MIME_TYPE_AUDIO_MID();
  static private native String MIME_TYPE_AUDIO_MPEG();
  static private native String MIME_TYPE_AUDIO_X_AIFF();
  static private native String MIME_TYPE_AUDIO_X_MPEGURL();
  static private native String MIME_TYPE_AUDIO_X_WAV();
  static private native String MIME_TYPE_IMAGE_BMP();
  static private native String MIME_TYPE_IMAGE_CIS_COD();
  static private native String MIME_TYPE_IMAGE_GIF();
  static private native String MIME_TYPE_IMAGE_IEF();
  static private native String MIME_TYPE_IMAGE_JPEG();
  static private native String MIME_TYPE_IMAGE_PIPEG();
  static private native String MIME_TYPE_IMAGE_SVG_XML();
  static private native String MIME_TYPE_IMAGE_TIFF();
  static private native String MIME_TYPE_IMAGE_X_CMX();
  static private native String MIME_TYPE_IMAGE_X_ICON();
  static private native String MIME_TYPE_IMAGE_X_RGB();
  static private native String MIME_TYPE_IMAGE_X_XBITMAP();
  static private native String MIME_TYPE_IMAGE_X_XPIXMAP();
  static private native String MIME_TYPE_IMAGE_X_XWINDOWDUMP();
  static private native String MIME_TYPE_MESSAGE_RFC822();
  static private native String MIME_TYPE_TEXT_CSS();
  static private native String MIME_TYPE_TEXT_H323();
  static private native String MIME_TYPE_TEXT_HTML();
  static private native String MIME_TYPE_TEXT_IULS();
  static private native String MIME_TYPE_TEXT_PLAIN();
  static private native String MIME_TYPE_TEXT_RICHTEXT();
  static private native String MIME_TYPE_TEXT_SCRIPTLET();
  static private native String MIME_TYPE_TEXT_WEBVIEWHTML();
  static private native String MIME_TYPE_TEXT_X_COMPONENT();
  static private native String MIME_TYPE_TEXT_X_SETEXT();
  static private native String MIME_TYPE_TEXT_X_VCARD();
  static private native String MIME_TYPE_VIDEO_MPEG();
  static private native String MIME_TYPE_VIDEO_QUICKTIME();
  static private native String MIME_TYPE_VIDEO_X_MSVIDEO();

}
