import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

SOURCES=['c/tk_jni.c']
env.SharedLibrary(os.path.join(LIB_DIR, 'awtk-jni'), SOURCES)





